# Generated by Django 3.2.3 on 2021-07-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=30, null=True)),
                ('Content', models.CharField(blank=True, max_length=30, null=True)),
                ('Created_on', models.DateTimeField(auto_now_add=True)),
                ('Thumbnail', models.ImageField(upload_to='thumbnail/')),
                ('Author', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
