# Generated by Django 3.2.3 on 2021-07-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='Content',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
