# Generated by Django 3.2.3 on 2021-07-07 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='Slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='Content',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
