# Generated by Django 3.2.3 on 2021-07-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_comment_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='dp',
            field=models.FileField(default=2, upload_to='dp/'),
            preserve_default=False,
        ),
    ]
