# Generated by Django 3.2.3 on 2021-08-11 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='keyword',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
